-- Catalyst Mom: seed SEO blog drafts (status='draft', publish from /admin)
-- Generated by scripts/seed-blog-drafts.mjs --sql
-- Safe to re-run: existing slugs are skipped.
INSERT INTO public.blogs (title, slug, excerpt, content, tags, featured_image_url, author, status)
VALUES
(
  'How to Use a Birth Ball to Help Induce Labor',
  'birth-ball-to-induce-labor',
  'Can bouncing on a birth ball really kickstart labor? What the research says, the movements midwives recommend, and how to do them safely at home.',
  '<h2>Can a Birth Ball Really Induce Labor?</h2>
<p>Short answer: a birth ball will not flip a switch and start labor on its own — no tool can. But research and midwife experience agree that birth ball movements can help create the <strong>conditions</strong> labor needs: an open pelvis, a well-positioned baby, and gentle, consistent pressure on the cervix.</p>
<p>A randomized study of first-time mothers found that women who used birth ball exercises had a meaningfully shorter average labor (about 14.4 hours vs 19.2 hours in the control group) and reported less pain. So while "induce" is too strong a word, "prepare and encourage" is exactly right.</p>

<h2>How It Works</h2>
<ul>
<li><strong>Opens the pelvis.</strong> Sitting upright on the ball with knees below hips widens the pelvic outlet, giving baby room to descend.</li>
<li><strong>Encourages optimal positioning.</strong> Gentle rocking and circles help baby rotate into the head-down, back-facing-front position that makes labor smoother.</li>
<li><strong>Applies cervical pressure.</strong> As baby drops lower, the head presses on the cervix — the natural signal that stimulates contractions.</li>
<li><strong>Relaxes you.</strong> Tension slows labor. Rhythmic movement releases it.</li>
</ul>

<h2>The 4 Movements to Try (From 37+ Weeks, With Your Provider''s OK)</h2>
<h3>1. Gentle Bouncing</h3>
<p>Sit tall, feet flat and shoulder-width apart, and bounce softly for 5–10 minutes. Think rhythm, not height.</p>
<h3>2. Hip Circles</h3>
<p>Circle your hips slowly in one direction for a minute, then reverse. This is the classic midwife-recommended move for helping baby settle into the pelvis.</p>
<h3>3. Figure 8s</h3>
<p>Trace a figure 8 with your hips. It combines the benefits of circles in both directions and feels wonderful on a tight lower back.</p>
<h3>4. Supported Lean (Kneeling)</h3>
<p>Kneel on a cushion and drape your chest over the ball, rocking gently. Great for back labor prep, and a perfect position for your partner to massage your lower back.</p>

<h2>Safety First</h2>
<ul>
<li>Wait until at least 37 weeks before doing labor-encouraging movements, and clear it with your midwife or OB first.</li>
<li>Make sure your ball is the right size — hips level with or slightly above knees. See our <a href="/birth-ball-guide/buying-guide">birth ball buying guide</a> for sizing by height.</li>
<li>Place the ball on carpet or a yoga mat, never a slick floor.</li>
<li>Stop if you feel pain, dizziness, or notice reduced baby movement.</li>
</ul>

<h2>Keep Going</h2>
<p>Want guided routines with pictures and timers? Our free <a href="/birth-ball-guide">Birth Ball Guide</a> includes trimester-by-trimester exercises, an <a href="/birth-ball-guide/early-labor">early labor section</a>, and a <a href="/birth-ball-guide/breathing-practice">breathing practice</a> to pair with every movement.</p>
<p><em>This article is for educational purposes only and is not medical advice. Always consult your healthcare provider before starting or changing any exercise, nutrition, or fertility plan.</em></p>',
  ARRAY['pregnancy', 'birth ball', 'labor'],
  'https://images.unsplash.com/photo-1530530824905-661c730c77e0?auto=format&fit=crop&w=1200&q=80',
  'Catalyst Mom Team',
  'draft'
),
(
  'Peanut Ball vs Birth Ball: Which One Do You Actually Need?',
  'peanut-ball-vs-birth-ball',
  'They both live in delivery rooms, but a peanut ball and a birth ball do very different jobs. Here is how to choose — or why you might want both.',
  '<h2>The Quick Answer</h2>
<p>A <strong>birth ball</strong> (round) is for <em>active, upright movement</em> — sitting, bouncing, rocking, and hip circles during pregnancy and early labor. A <strong>peanut ball</strong> (peanut-shaped) is for <em>resting positions</em> — it goes between your knees while you lie on your side, keeping the pelvis open when you cannot be upright, such as with an epidural.</p>

<h2>Side-by-Side Comparison</h2>
<table>
<thead><tr><th></th><th>Birth Ball</th><th>Peanut Ball</th></tr></thead>
<tbody>
<tr><td><strong>Shape</strong></td><td>Round</td><td>Peanut / hourglass</td></tr>
<tr><td><strong>Best for</strong></td><td>Pregnancy comfort, active labor, postpartum exercise</td><td>Labor with an epidural, side-lying rest</td></tr>
<tr><td><strong>How you use it</strong></td><td>Sit and move on it</td><td>Place between knees while lying down</td></tr>
<tr><td><strong>Evidence</strong></td><td>Shorter labor, less pain in studies</td><td>Studies show faster dilation and fewer cesareans when used with epidurals</td></tr>
<tr><td><strong>Use after birth?</strong></td><td>Yes — core rehab, soothing baby</td><td>Rarely</td></tr>
</tbody>
</table>

<h2>When the Birth Ball Wins</h2>
<p>If you are buying one tool for pregnancy through postpartum, get the round ball. You can use it from the first trimester for posture and back pain, through labor for movement, and afterward for gentle core work and even bouncing a fussy newborn. Start with our <a href="/birth-ball-guide">complete birth ball guide</a> and make sure you get the right size in the <a href="/birth-ball-guide/buying-guide">buying guide</a>.</p>

<h2>When the Peanut Ball Wins</h2>
<p>If you are planning an epidural or know you will labor mostly in bed, ask whether your hospital provides peanut balls (many do). Tucked between your knees in a side-lying position, it keeps the pelvic outlet open so baby can keep descending even while you rest.</p>

<h2>The Real Answer for Most Moms</h2>
<p>Own a birth ball; borrow the hospital''s peanut ball. You get daily value from the round ball for months, while the peanut ball shines for a matter of hours — and the hospital usually has one waiting.</p>

<h2>Sizing Cheat Sheet</h2>
<ul>
<li>Under 5''3": 55 cm ball</li>
<li>5''4"–5''9": 65 cm ball</li>
<li>5''10" and taller: 75 cm ball</li>
</ul>
<p>Check the fit: sitting on the ball, your hips should be level with or slightly higher than your knees. More sizing help and anti-burst safety tips in our <a href="/birth-ball-guide/safety">safety guide</a> and <a href="/birth-ball-guide/faq">FAQ</a>.</p>
<p><em>This article is for educational purposes only and is not medical advice. Always consult your healthcare provider before starting or changing any exercise, nutrition, or fertility plan.</em></p>',
  ARRAY['pregnancy', 'birth ball', 'labor'],
  'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1200&q=80',
  'Catalyst Mom Team',
  'draft'
),
(
  'Diastasis Recti Exercises: Rebuild Your Core After Baby',
  'diastasis-recti-exercises',
  'Ab separation does not heal with crunches. These evidence-backed deep-core exercises restore strength, rebuild tension, and help close the gap.',
  '<h2>What Diastasis Recti Actually Is</h2>
<p>During pregnancy, the connective tissue between your "six-pack" muscles (the linea alba) stretches to make room for baby. For about 60% of moms, that separation — diastasis recti — persists after birth. The result: a soft belly that will not flatten, a doming ridge when you sit up, low-back pain, or a core that just feels disconnected.</p>
<p>Here is the reframe that changes everything: healing is less about <em>closing the gap</em> and more about <em>rebuilding tension</em> across it with your deepest abdominal layer, the transverse abdominis (TVA).</p>

<h2>First: Check Your Gap</h2>
<p>Before starting, do a 60-second self-check (full instructions in our <a href="/blog/how-to-check-diastasis-recti-at-home">at-home diastasis test guide</a>). Knowing your starting width and depth lets you track real progress.</p>

<h2>The 5 Foundational Exercises</h2>
<h3>1. Diaphragmatic Breathing with TVA Engagement</h3>
<p>Lie on your back, knees bent. Inhale into your ribs and belly. As you exhale, gently draw your belly button toward your spine — like hugging baby with your abs, not sucking in. Hold 5 seconds. 10 reps. This breath is the foundation of every other exercise.</p>
<h3>2. Heel Slides</h3>
<p>Same position. Exhale, engage your TVA, and slowly slide one heel along the floor until the leg is straight, then return. Alternate. 8–10 per side. The challenge: keep your core engaged so your back never arches.</p>
<h3>3. Glute Bridges</h3>
<p>Exhale, engage, and lift your hips into a bridge. Hold 3 seconds, lower with control. 10–12 reps. Strong glutes take pressure off the healing midline.</p>
<h3>4. Modified Side Plank</h3>
<p>From your side with knees bent, lift your hips, keeping shoulder over elbow. Hold 10–15 seconds per side. Side work strengthens obliques without straining the linea alba.</p>
<h3>5. Bird Dog</h3>
<p>On hands and knees, exhale and extend opposite arm and leg while keeping hips level. Slow and controlled, 6–8 per side.</p>

<h2>The Rules That Protect Your Healing</h2>
<ul>
<li><strong>No doming, ever.</strong> If your belly cones or ridges during a movement, the load is too much. Regress and rebuild.</li>
<li><strong>Exhale on effort.</strong> Holding your breath spikes intra-abdominal pressure right at the weakest point.</li>
<li><strong>Skip crunches, sit-ups, and front planks</strong> until tension is restored — see the full <a href="/blog/exercises-to-avoid-diastasis-recti">list of exercises to avoid</a>.</li>
<li><strong>Consistency beats intensity.</strong> 10 focused minutes daily outperforms one hard weekly session.</li>
</ul>

<h2>Want a Structured Plan?</h2>
<p>Our <a href="/workouts/core-restore-foundations">Core Restore Foundations program</a> walks you through this exact progression week by week, with video coaching and built-in checkpoints. If you are more than 8 weeks postpartum and seeing no change, a pelvic floor physical therapist is worth every penny.</p>

<h2>How Long Does Recovery Take?</h2>
<p>With consistent daily work, most moms see meaningful change in <strong>6–12 weeks</strong>: the gap narrows, the midline firms up, and everyday movements stop feeling unstable. Full return to high-impact exercise commonly takes 3–6 months. Two honest caveats: progress is rarely linear (hormones, sleep, and carrying a growing baby all tug at it), and a small, firm residual gap is completely compatible with a strong, pain-free core. Function beats centimeters.</p>

<h2>Your First 4 Weeks: A Sample Progression</h2>
<table>
<thead><tr><th>Week</th><th>Daily focus (about 10 minutes)</th></tr></thead>
<tbody>
<tr><td>1</td><td>Breathing with TVA engagement only — 3 sets of 10, morning and evening. Learn the exhale-engage pattern until it is automatic.</td></tr>
<tr><td>2</td><td>Add heel slides (8 per side) and glute bridges (10). Keep checking: no doming.</td></tr>
<tr><td>3</td><td>Add modified side planks (3 x 10 seconds per side). Increase bridge holds to 5 seconds.</td></tr>
<tr><td>4</td><td>Add bird dogs (6 per side). Re-test your gap and compare width <em>and</em> tension to week 0.</td></tr>
</tbody>
</table>
<p>From week 5 onward, progress one variable at a time — longer holds, more reps, then more challenging positions. The <a href="/workouts/core-restore-foundations">Core Restore Foundations program</a> continues this progression through full strength training.</p>

<h2>Beyond Exercise: Habits That Speed Healing</h2>
<ul>
<li><strong>Posture resets.</strong> Stack ribs over pelvis when standing and feeding. A rib cage flared toward the ceiling keeps constant stretch on the midline.</li>
<li><strong>Smart lifting mechanics.</strong> Bring baby (and car seat) close to your body, exhale as you lift, and avoid twisting mid-lift.</li>
<li><strong>Manage constipation.</strong> Straining is a direct pressure spike on the healing midline — fiber, water, and a footstool under your feet genuinely matter here. Our <a href="/meal-plan">meal plan tool</a> can build a fiber-forward week.</li>
<li><strong>Sleep and protein.</strong> Connective tissue rebuilds with collagen, and collagen needs protein and rest. Aim for protein at every meal.</li>
</ul>

<h2>Diastasis Recti FAQ</h2>
<h3>Can diastasis recti heal years after pregnancy?</h3>
<p>Yes. The same deep-core retraining works whether you are 6 weeks or 6 years postpartum. Older diastasis often takes a little longer because compensation habits are ingrained, but the tissue still responds to progressive loading.</p>
<h3>Will a waist trainer or binder fix it?</h3>
<p>No. Compression garments can give comfort and gentle support in early postpartum, but they do not strengthen anything — and aggressive waist trainers can push pressure downward onto the pelvic floor. Use a soft wrap as scaffolding while you do the exercises, not instead of them.</p>
<h3>Can I lift weights with diastasis recti?</h3>
<p>Yes, with two rules: exhale and engage before every rep, and choose loads where you can keep a flat midline (no doming). Many moms get stronger throughout recovery — the lifts just get selected and scaled deliberately.</p>
<h3>When should I see a pelvic floor physical therapist?</h3>
<p>If your gap is wider than four fingers, feels deep and soft with no improvement after 6–8 weeks of consistent work, or you have pain, bulging, or leaking, book the appointment. One assessment usually pays for itself in months of better-targeted work.</p>
<p><em>This article is for educational purposes only and is not medical advice. Always consult your healthcare provider before starting or changing any exercise, nutrition, or fertility plan.</em></p>',
  ARRAY['postpartum', 'fitness', 'core'],
  'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=80',
  'Catalyst Mom Team',
  'draft'
),
(
  'How to Check for Diastasis Recti at Home (60-Second Test)',
  'how-to-check-diastasis-recti-at-home',
  'A simple finger-width test you can do on your living room floor tells you whether you have ab separation, how wide it is, and what to do next.',
  '<h2>The 60-Second Test</h2>
<ol>
<li><strong>Lie on your back</strong>, knees bent, feet flat on the floor.</li>
<li><strong>Place your fingers</strong> horizontally just above your belly button, fingertips pointing down toward your spine.</li>
<li><strong>Lift your head and shoulders</strong> slightly off the floor — just enough to feel your ab muscles tense on either side of your fingers.</li>
<li><strong>Feel the gap.</strong> How many finger-widths fit between the two muscle ridges? Note the width <em>and</em> the depth (does the tissue feel firm and springy, or soft and squishy?).</li>
<li><strong>Repeat</strong> 2 inches above the belly button and 2 inches below — separation can vary along the midline.</li>
</ol>

<h2>Reading Your Results</h2>
<table>
<thead><tr><th>Gap width</th><th>What it means</th></tr></thead>
<tbody>
<tr><td>1 finger or less</td><td>Normal — no diastasis</td></tr>
<tr><td>2 fingers</td><td>Mild separation — very common, responds well to exercise</td></tr>
<tr><td>2–3 fingers</td><td>Moderate diastasis — start a structured deep-core program</td></tr>
<tr><td>4+ fingers, or very soft/deep</td><td>See a pelvic floor physical therapist for an individual plan</td></tr>
</tbody>
</table>
<p><strong>Depth matters as much as width.</strong> A 2-finger gap with firm tension underneath is healthier than a 1-finger gap that feels like a soft trench. The goal of rehab is tension, not just narrowing.</p>

<h2>Other Signs Worth Noticing</h2>
<ul>
<li>A visible ridge or "doming" down your midline when you sit up out of bed</li>
<li>A belly that still looks pregnant months after birth despite weight loss</li>
<li>Low-back pain, hip pain, or a feeling of core weakness</li>
<li>Leaking urine when you sneeze or jump (often a companion pelvic floor issue)</li>
</ul>

<h2>When to Test</h2>
<p>Wait until at least 2–3 weeks postpartum — everything is naturally lax before then. Re-test every 2 weeks while doing core rehab so you can see progress in both width and tension.</p>

<h2>What to Do With Your Result</h2>
<p>If you found a gap, do not panic and do not start crunches. Begin with breath-led deep core work — our guide to <a href="/blog/diastasis-recti-exercises">safe diastasis recti exercises</a> covers the exact starting moves, and the <a href="/workouts/core-restore-foundations">Core Restore Foundations program</a> turns them into a progressive weekly plan.</p>
<p><em>This article is for educational purposes only and is not medical advice. Always consult your healthcare provider before starting or changing any exercise, nutrition, or fertility plan.</em></p>',
  ARRAY['postpartum', 'core'],
  'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=80',
  'Catalyst Mom Team',
  'draft'
),
(
  '9 Exercises to Avoid With Diastasis Recti (+ Safe Swaps)',
  'exercises-to-avoid-diastasis-recti',
  'Some popular ab exercises actively widen ab separation. Here are nine to skip while you heal — each with a safe swap that trains the same muscles.',
  '<h2>Why Some Exercises Make the Gap Worse</h2>
<p>Diastasis recti heals when you build tension in the deep core <em>without</em> spiking pressure against the stretched midline. Any movement that bulges your belly outward, cones your midline, or loads your core before it can resist that load works against you. The test is simple: <strong>if you see doming, stop.</strong></p>

<h2>Skip These — Do These Instead</h2>
<table>
<thead><tr><th>Avoid for now</th><th>Why</th><th>Safe swap</th></tr></thead>
<tbody>
<tr><td>Crunches & sit-ups</td><td>Maximum pressure right on the gap</td><td>Heel slides</td></tr>
<tr><td>Full front planks</td><td>Gravity drags the belly down, doming the midline</td><td>Modified side plank</td></tr>
<tr><td>Double leg lifts</td><td>Long lever overwhelms a weak TVA</td><td>Single-leg heel taps</td></tr>
<tr><td>Russian twists</td><td>Loaded rotation shears the linea alba</td><td>Bird dog</td></tr>
<tr><td>Bicycle crunches</td><td>Flexion + rotation, the worst combo</td><td>Dead bug (single side)</td></tr>
<tr><td>Push-ups (full)</td><td>Same problem as front planks</td><td>Wall or incline push-ups</td></tr>
<tr><td>Heavy overhead lifting</td><td>Breath-holding spikes intra-abdominal pressure</td><td>Lighter weights, exhale on effort</td></tr>
<tr><td>Boat pose / v-sits</td><td>Sustained flexion under load</td><td>Glute bridges</td></tr>
<tr><td>High-impact running or jumping (early on)</td><td>Repetitive downward pressure on core and pelvic floor</td><td>Incline walking — track it in your <a href="/workout-plan">workout plan</a></td></tr>
</tbody>
</table>

<h2>Three Habits That Matter as Much as Exercise</h2>
<ul>
<li><strong>Roll, don''t crunch, out of bed.</strong> Roll to your side first, then push up with your arm. Every sit-up-style bed exit is an unplanned crunch.</li>
<li><strong>Exhale when you lift</strong> — baby, car seat, laundry. Pair effort with breath out and a gentle belly draw-in.</li>
<li><strong>Watch your posture.</strong> Rib-thrusting and constant belly-sucking both disrupt the pressure system your core needs to heal.</li>
</ul>

<h2>When Can I Go Back to Normal Workouts?</h2>
<p>When you can do the foundational moves with zero doming and your gap shows firm tension (re-test with our <a href="/blog/how-to-check-diastasis-recti-at-home">self-check guide</a>), begin re-introducing harder exercises one at a time. The <a href="/workouts/core-restore-foundations">Core Restore Foundations program</a> sequences this return for you, from first breath work to full strength training.</p>
<p><em>This article is for educational purposes only and is not medical advice. Always consult your healthcare provider before starting or changing any exercise, nutrition, or fertility plan.</em></p>',
  ARRAY['postpartum', 'fitness', 'core'],
  'https://images.unsplash.com/photo-1571190264779-8fed513b7c91?auto=format&fit=crop&w=1200&q=80',
  'Catalyst Mom Team',
  'draft'
),
(
  'C-Section Recovery Exercises: A Week-by-Week Guide',
  'c-section-recovery-exercises-week-by-week',
  'A cesarean is major surgery — your comeback should respect that. This week-by-week guide rebuilds your core safely from day one to month three.',
  '<h2>The Golden Rule</h2>
<p>A cesarean cuts through skin, fascia, and the uterine wall. Healing takes a minimum of 6 weeks for the surface and months for deep tissue. The plan below is a typical progression — <strong>your OB clears each phase, not the calendar.</strong> Pain, pulling at the incision, or increased bleeding means step back.</p>

<h2>Weeks 1–2: Breathe, Walk, Heal</h2>
<ul>
<li><strong>Diaphragmatic breathing</strong>, several times a day. Inhale into the ribs; exhale with the gentlest lower-belly engagement. This reconnects your brain to your core and improves circulation for healing.</li>
<li><strong>Short, flat walks</strong> — start with 5 minutes, add a few minutes daily as comfort allows.</li>
<li><strong>Ankle pumps and gentle leg movement</strong> to support circulation.</li>
<li>Support your incision with a pillow when coughing, laughing, or sneezing.</li>
</ul>

<h2>Weeks 3–4: Wake Up the Deep Core</h2>
<ul>
<li><strong>Pelvic tilts</strong> lying on your back — flatten your low back into the floor on the exhale, 10 reps.</li>
<li><strong>Pelvic floor activations</strong> (gentle Kegels): squeeze, hold 3–5 seconds, fully relax. The pelvic floor and cesarean recovery are partners, not separate projects.</li>
<li><strong>Seated marches</strong> and longer walks, 15–20 minutes.</li>
</ul>

<h2>Weeks 5–6: Foundation Strength (With Clearance)</h2>
<ul>
<li><strong>Heel slides</strong> — 8–10 per side, core gently engaged.</li>
<li><strong>Glute bridges</strong> — 10–12 slow reps.</li>
<li><strong>Wall push-ups</strong> — upper body strength without core strain.</li>
<li>Check for diastasis recti with our <a href="/blog/how-to-check-diastasis-recti-at-home">60-second self-test</a>; cesarean moms get it too.</li>
</ul>

<h2>Weeks 7–12: Progressive Rebuild</h2>
<ul>
<li>Add <strong>bird dogs, modified side planks, squats to a chair, and resistance bands</strong>.</li>
<li>Walk briskly 30+ minutes; stationary cycling is a great low-impact add.</li>
<li>Hold off on running, jumping, and heavy lifting until roughly 12 weeks <em>and</em> you pass the basics without doming, pain, or leaking.</li>
</ul>

<h2>Red Flags — Call Your Provider</h2>
<ul>
<li>Incision redness, warmth, discharge, or opening</li>
<li>Pain that increases rather than fades</li>
<li>Bleeding that restarts or intensifies after activity</li>
<li>Fever, or a bulge near the scar</li>
</ul>

<h2>Make It a Plan, Not a Guess</h2>
<p>Our <a href="/workouts/core-restore-foundations">Core Restore Foundations program</a> is built for exactly this comeback, and the <a href="/workout-plan">workout plan builder</a> can schedule your weekly progression around real life with a newborn.</p>
<p><em>This article is for educational purposes only and is not medical advice. Always consult your healthcare provider before starting or changing any exercise, nutrition, or fertility plan.</em></p>',
  ARRAY['postpartum', 'fitness'],
  'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1200&q=80',
  'Catalyst Mom Team',
  'draft'
),
(
  '7-Day Breastfeeding Meal Plan for New Moms',
  'breastfeeding-meal-plan-7-day',
  'Breastfeeding burns 300-500 extra calories a day. This realistic one-week meal plan keeps you nourished and your supply strong - no cooking marathons required.',
  '<h2>What Your Body Needs Right Now</h2>
<p>Milk production is metabolically expensive: most nursing moms need an extra <strong>300–500 calories a day</strong> (roughly 2,200–2,400 total), plus elevated protein, calcium, iron, choline, iodine, and omega-3s. And hydration is non-negotiable — aim for about <strong>13 cups of fluids daily</strong>. A water bottle at every nursing station is the easiest habit win.</p>

<h2>The Plan at a Glance</h2>
<p>Every day follows the same simple skeleton, so there is nothing to memorize: <strong>3 meals + 2–3 snacks</strong>, each anchored by protein, fiber, and a healthy fat.</p>
<table>
<thead><tr><th>Day</th><th>Breakfast</th><th>Lunch</th><th>Dinner</th></tr></thead>
<tbody>
<tr><td>Mon</td><td>Overnight oats + chia, berries, almond butter</td><td>Chicken & quinoa grain bowl</td><td>Salmon, roasted sweet potato, broccoli</td></tr>
<tr><td>Tue</td><td>Greek yogurt, granola, banana</td><td>Lentil soup + whole grain toast</td><td>Slow-cooker chicken & veggie stew</td></tr>
<tr><td>Wed</td><td>Veggie omelet + avocado toast</td><td>Leftover stew (cook once, eat twice)</td><td>Turkey chili with beans</td></tr>
<tr><td>Thu</td><td>Oatmeal with flax, walnuts, apple</td><td>Tuna-white bean salad wrap</td><td>Stir-fry: beef or tofu, brown rice</td></tr>
<tr><td>Fri</td><td>Smoothie: spinach, banana, oats, peanut butter, milk</td><td>Leftover stir-fry</td><td>Sheet-pan chicken, potatoes, green beans</td></tr>
<tr><td>Sat</td><td>Whole grain pancakes + berries + yogurt</td><td>Hummus, veggie & feta pita</td><td>Baked white fish, couscous, salad</td></tr>
<tr><td>Sun</td><td>Scrambled eggs, spinach, toast</td><td>Big grain bowl with leftovers</td><td>Pasta with turkey meat sauce + side salad</td></tr>
</tbody>
</table>

<h2>Snack Bank (Grab Two Daily)</h2>
<ul>
<li>Trail mix or a handful of almonds + dried fruit</li>
<li>Lactation-friendly oat energy balls (oats, peanut butter, flax, honey)</li>
<li>Greek yogurt cup or string cheese + fruit</li>
<li>Hummus with cut veggies or whole grain crackers</li>
<li>Hard-boiled eggs (cook 6 on Sunday)</li>
</ul>

<h2>Why These Foods</h2>
<p>Oats, flax, lentils, and leafy greens appear all week on purpose — they are the foods most consistently linked with healthy supply. The full breakdown is in our guide to <a href="/blog/foods-to-increase-milk-supply">foods that support milk supply</a>.</p>

<h2>Survival-Mode Shortcuts</h2>
<ul>
<li><strong>Cook once, eat twice:</strong> every dinner above intentionally produces leftovers.</li>
<li><strong>One-dish wins:</strong> soups, sheet pans, and slow-cooker meals cut cleanup when you are one-handed with a baby.</li>
<li><strong>Accept the lasagna.</strong> When friends offer food, say yes.</li>
</ul>
<p>Want this customized to your preferences, allergies, and calorie needs? Build yours with the <a href="/meal-plan">Catalyst Mom meal plan tool</a>, and check any food quickly with the <a href="/food-calories">food calorie checker</a>.</p>
<p><em>This article is for educational purposes only and is not medical advice. Always consult your healthcare provider before starting or changing any exercise, nutrition, or fertility plan.</em></p>',
  ARRAY['nutrition', 'postpartum'],
  'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',
  'Catalyst Mom Team',
  'draft'
),
(
  '12 Foods That Support Milk Supply, Backed by Science',
  'foods-to-increase-milk-supply',
  'From oats to flaxseed, here are the foods with real evidence (or at least real nutrition) behind their milk-boosting reputation - and how to eat more of them.',
  '<h2>First, the Honest Truth</h2>
<p>No food outranks the two real drivers of supply: <strong>frequent, effective milk removal</strong> and <strong>enough calories and fluids overall</strong>. But within a well-fed day, certain foods earn their reputation — either through emerging evidence or because they deliver exactly the nutrients lactation drains. Here are the twelve worth keeping in rotation.</p>

<h2>The List</h2>
<h3>1. Oats</h3>
<p>The classic. Rich in iron, fiber, and beta-glucans, which may support prolactin — the hormone that drives production. Overnight oats are the perfect one-handed breakfast.</p>
<h3>2. Flaxseed</h3>
<p>Omega-3s plus phytoestrogens. Stir ground flax into oatmeal, yogurt, or smoothies.</p>
<h3>3. Lentils</h3>
<p>Iron + protein + fiber in one cheap pantry staple. Low iron is linked with fatigue and supply struggles.</p>
<h3>4. Leafy Greens</h3>
<p>Spinach and kale bring calcium, iron, and folate. Blend into smoothies if salads feel impossible right now.</p>
<h3>5. Salmon</h3>
<p>DHA for baby''s brain via your milk, plus vitamin D and protein. Two servings a week of low-mercury fish is the standard guidance.</p>
<h3>6. Eggs</h3>
<p>One of the best sources of choline, a nutrient most nursing moms under-consume.</p>
<h3>7. Nuts and Nut Butters</h3>
<p>Calorie-dense healthy fats — exactly what a 500-calorie daily deficit calls for.</p>
<h3>8. Greek Yogurt</h3>
<p>Protein + calcium + probiotics. Lactation pulls calcium from your bones if you do not replace it.</p>
<h3>9. Sweet Potatoes</h3>
<p>Vitamin A (critical for baby''s development) and steady-energy carbs.</p>
<h3>10. Fennel</h3>
<p>Traditional galactagogue with small supportive studies. Roast it, or sip fennel tea.</p>
<h3>11. Barley</h3>
<p>The richest common source of beta-glucan. Swap it for rice in soups.</p>
<h3>12. Water (Honorary Member)</h3>
<p>Milk is ~90% water. Aim for 13 cups of fluids a day; chronic mild dehydration is the most common invisible supply saboteur.</p>

<h2>Put It Together</h2>
<p>You will find these foods woven through our <a href="/blog/breastfeeding-meal-plan-7-day">7-day breastfeeding meal plan</a>, or you can generate a personalized week with the <a href="/meal-plan">meal plan tool</a>.</p>

<h2>When Food Is Not Enough</h2>
<p>If supply is genuinely struggling — slow weight gain, fewer wet diapers — see a lactation consultant before relying on any food or supplement. Latch and feeding frequency fix more supply problems than every galactagogue combined.</p>
<p><em>This article is for educational purposes only and is not medical advice. Always consult your healthcare provider before starting or changing any exercise, nutrition, or fertility plan.</em></p>',
  ARRAY['nutrition', 'postpartum'],
  'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1200&q=80',
  'Catalyst Mom Team',
  'draft'
),
(
  '25 Five-Minute Self-Care Ideas for Moms Who Have No Time',
  'self-care-ideas-busy-moms',
  'Self-care that requires a babysitter is not a plan. These 25 micro-practices fit inside nap time, car line, and the 5 minutes before everyone wakes up.',
  '<h2>The Mindset Shift</h2>
<p>Research on maternal burnout is clear: small, <em>repeated</em> acts of self-kindness reduce exhaustion and stress more reliably than rare grand gestures. You do not need a spa day. You need 5 minutes, several times a day, claimed on purpose.</p>

<h2>Reset Your Nervous System (1–5 minutes)</h2>
<ol>
<li>Three slow, deep breaths in the car before walking into the house.</li>
<li>Step outside and feel the air for one full minute. That is it. That counts.</li>
<li>Drink a glass of water slowly, doing nothing else.</li>
<li>A 4-7-8 breath cycle: inhale 4, hold 7, exhale 8 — repeat four times.</li>
<li>Put one hand on your heart, close your eyes, and name three things you did right today.</li>
</ol>

<h2>Move Your Body (Without "Working Out")</h2>
<ol start="6">
<li>Stretch your shoulders while the microwave runs.</li>
<li>Ten slow squats while coffee brews.</li>
<li>A barefoot walk on grass with the baby in your arms.</li>
<li>Dance to one song in the kitchen — bonus if the kids join.</li>
<li>Lie on the floor, legs up the wall, for five minutes.</li>
</ol>

<h2>Feed Your Mind</h2>
<ol start="11">
<li>Read five pages of an actual book.</li>
<li>Journal three sentences: how you feel, what you need, one tiny win.</li>
<li>Listen to a podcast on headphones during one chore.</li>
<li>Sit in silence. No phone. Ninety seconds.</li>
<li>Write tomorrow''s one most-important thing on a sticky note — then stop planning.</li>
</ol>

<h2>Stay Connected</h2>
<ol start="16">
<li>Voice-message a friend instead of doom-scrolling.</li>
<li>Schedule one monthly coffee date and protect it like a pediatric appointment.</li>
<li>Say one honest sentence to your partner about how today actually went.</li>
<li>Join a conversation in the <a href="/community">Catalyst Mom community</a> — moms who get it, on your schedule.</li>
<li>Hug someone for a full ten seconds.</li>
</ol>

<h2>Small Luxuries</h2>
<ol start="21">
<li>The good lotion, applied slowly.</li>
<li>Tea in your favorite mug, hot, finished while still hot.</li>
<li>A two-minute face massage while moisturizing.</li>
<li>Fresh socks mid-afternoon (do not knock it until you try it).</li>
<li>Go to bed fifteen minutes earlier and call it what it is: self-care.</li>
</ol>

<h2>Make It Stick</h2>
<p>Anchor each practice to something you already do — feed the baby, then drink the water; start the dishwasher, then stretch. Explore more guided practices in our <a href="/wellness/self-care">self-care hub</a> and track how you feel in your <a href="/dashboard">wellness dashboard</a>.</p>
<p><em>This article is for educational purposes only and is not medical advice. Always consult your healthcare provider before starting or changing any exercise, nutrition, or fertility plan.</em></p>',
  ARRAY['wellness', 'postpartum'],
  'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80',
  'Catalyst Mom Team',
  'draft'
),
(
  'How to Track Ovulation When TTC: 5 Methods Ranked',
  'how-to-track-ovulation-ttc',
  'Your fertile window is about six days a month. Finding it is the highest-impact thing you can do while TTC. Every tracking method, ranked.',
  '<h2>Why Tracking Changes Everything</h2>
<p>Pregnancy is only possible during the <strong>fertile window</strong>: the five days before ovulation, the day of ovulation, and roughly a day after. Sperm survive up to five days; the egg lasts about 24 hours. Your best odds come from intercourse in the 1–2 days <em>before</em> ovulation — which means predicting it, not just spotting it after the fact.</p>

<h2>Method 1: Calendar Tracking (Free, Start Here)</h2>
<p>Mark day one of each period and count cycle lengths for several months. Ovulation typically happens 12–14 days <em>before</em> your next period starts — not on "day 14" unless you happen to have a textbook 28-day cycle. Best as a rough map; do not rely on it alone if your cycles vary.</p>

<h2>Method 2: Cervical Mucus (Free, Surprisingly Accurate)</h2>
<p>As ovulation approaches, discharge turns clear, slippery, and stretchy — like raw egg white. That is peak fertility, happening in real time. It costs nothing and tells you exactly when to prioritize trying.</p>

<h2>Method 3: Basal Body Temperature (Cheap, Confirms After the Fact)</h2>
<p>Take your temperature at the same time every morning before getting up. After ovulation, progesterone raises BBT by about 0.5–1.0°F, and it stays elevated. BBT cannot predict ovulation — it confirms it happened, which over 2–3 months reveals your personal pattern. Note: interrupted sleep (hello, newborns and night shifts) makes BBT noisy.</p>

<h2>Method 4: Ovulation Predictor Kits (Most Bang for the Buck)</h2>
<p>OPK strips detect the LH surge that occurs 24–36 hours before ovulation. Testing daily for five days around your expected ovulation catches it about 80% of the time; ten days of testing pushes that to ~95%. Strips are cheap in bulk — start testing a few days before your earliest predicted ovulation day.</p>

<h2>Method 5: Apps and Wearables (Best for Irregular Cycles)</h2>
<p>Cycle apps combine your logged data with algorithms; wearables add overnight temperature and heart-rate trends. They shine when cycles are irregular and manual prediction keeps missing. Treat their predictions as hypotheses to confirm with mucus or OPKs, not gospel.</p>

<h2>The Power Combo</h2>
<p>Most fertility specialists suggest pairing <strong>cervical mucus + OPKs</strong> for prediction, with <strong>BBT</strong> as monthly confirmation. Track all three in your <a href="/dashboard">Catalyst Mom dashboard</a>, where our TTC pattern reports help you see your cycle trends over time.</p>

<h2>When to Loop In a Professional</h2>
<p>Under 35: after a year of well-timed trying. 35 or older: after six months. Sooner if your cycles are very irregular or absent — that is data worth investigating, not just working around. And while you are trying, our guide to <a href="/blog/how-to-get-pregnant-faster-ttc-tips">evidence-based TTC tips</a> covers the lifestyle side.</p>

<h2>A Sample One-Cycle Tracking Routine</h2>
<table>
<thead><tr><th>Cycle phase</th><th>What to do</th></tr></thead>
<tbody>
<tr><td>Day 1 (period starts)</td><td>Log it. This anchors every other calculation.</td></tr>
<tr><td>Days 1–7</td><td>Take BBT each morning before getting up. Nothing else needed yet.</td></tr>
<tr><td>About 5 days before expected ovulation</td><td>Start daily OPK strips (same time each afternoon) and begin checking cervical mucus.</td></tr>
<tr><td>Positive OPK or egg-white mucus</td><td>This is the green light — prioritize the next 2–3 days.</td></tr>
<tr><td>2–3 days after suspected ovulation</td><td>Look for the sustained BBT rise that confirms ovulation happened.</td></tr>
<tr><td>End of cycle</td><td>Review the month: did the OPK, mucus, and temperature shift agree? Each cycle sharpens next month''s prediction.</td></tr>
</tbody>
</table>

<h2>5 Common Tracking Mistakes</h2>
<ol>
<li><strong>Assuming day 14.</strong> Ovulation timing varies enormously; track your body, not a textbook cycle.</li>
<li><strong>Testing OPKs with morning urine.</strong> The LH surge often starts mid-morning — early afternoon testing catches it more reliably.</li>
<li><strong>Taking BBT after getting up.</strong> Even a trip to the bathroom first can distort the reading. Thermometer on the nightstand, reading before your feet hit the floor.</li>
<li><strong>Stopping intercourse after the positive OPK.</strong> The surge means ovulation is coming in 24–36 hours — the next two days still count, a lot.</li>
<li><strong>Switching methods every month.</strong> Each method needs 2–3 cycles of your own data before its predictions get sharp. Pick a combo and stay with it.</li>
</ol>

<h2>Ovulation Tracking FAQ</h2>
<h3>Can I ovulate without ever getting a positive OPK?</h3>
<p>Yes. Some women have short LH surges that a once-a-day test misses. If your BBT shows a clear sustained rise but OPKs stay negative, trust the temperature pattern — or test twice daily around your expected surge.</p>
<h3>Can I get pregnant outside the fertile window?</h3>
<p>Conception requires an egg, so functionally no — but the window is wider than it feels because sperm survive up to five days. The practical takeaway: starting "too early" costs nothing; starting after ovulation usually misses the month.</p>
<h3>How do I track with irregular cycles?</h3>
<p>Lean on real-time signals (cervical mucus and OPKs) rather than calendar prediction, and give it more testing days. Persistently irregular or absent cycles deserve a medical conversation — they are the most common treatable cause of slow conception.</p>
<p><em>This article is for educational purposes only and is not medical advice. Always consult your healthcare provider before starting or changing any exercise, nutrition, or fertility plan.</em></p>',
  ARRAY['ttc', 'wellness'],
  'https://images.unsplash.com/photo-1506629905589-5d5b48f62a6a?auto=format&fit=crop&w=1200&q=80',
  'Catalyst Mom Team',
  'draft'
),
(
  'How to Get Pregnant Faster: 8 Evidence-Based Tips',
  'how-to-get-pregnant-faster-ttc-tips',
  'Skip the old wives tales. These are the conception strategies actually supported by research - timing, nutrition, lifestyle, and when to ask for help.',
  '<h2>The 8 Things That Actually Move the Needle</h2>
<h3>1. Nail the Timing</h3>
<p>This is 80% of the game. Have sex every day or every other day during your fertile window — the five days before ovulation through the day after. Find that window with our <a href="/blog/how-to-track-ovulation-ttc">ovulation tracking guide</a>.</p>
<h3>2. Start Folic Acid Now</h3>
<p>Prenatal vitamins with at least 400 mcg of folic acid matter <em>before</em> conception — neural tube development happens in the first weeks, often before a positive test.</p>
<h3>3. See Your Provider for a Preconception Check</h3>
<p>Medication review, vaccination status, thyroid, and any conditions like PCOS or endometriosis — fifteen minutes that can save months.</p>
<h3>4. Quit Smoking — Both Partners</h3>
<p>Tobacco measurably reduces egg quality and sperm count, and it is one of the most fixable fertility factors there is.</p>
<h3>5. Skip Alcohol While Trying</h3>
<p>The guidance keeps tightening: best evidence says none while actively trying, for both conception odds and earliest development.</p>
<h3>6. Eat Like It Matters</h3>
<p>A Mediterranean-style pattern — vegetables, whole grains, fish, olive oil, legumes — is associated with better fertility in both partners. Build a TTC-friendly week with the <a href="/meal-plan">meal plan tool</a>.</p>
<h3>7. Land in a Healthy Weight Range</h3>
<p>Both underweight and overweight can disrupt ovulation. Even a 5–10% weight change can restore regular cycles for some women. Gentle, consistent movement helps — our <a href="/workout-plan">workout plan builder</a> can keep it sustainable.</p>
<h3>8. Manage Stress (Without Being Told to "Just Relax")</h3>
<p>Chronic stress can disrupt the hormonal cascade behind ovulation. Mindfulness, sleep, walks, and community support are legitimate fertility tools — find your people in the <a href="/community">Catalyst Mom community</a>.</p>

<h2>3 Myths You Can Stop Worrying About</h2>
<ul>
<li><strong>"Lying with your legs up after sex helps."</strong> No evidence. Sperm reach the cervix within minutes regardless of gymnastics.</li>
<li><strong>"You should save up sperm by waiting between attempts."</strong> Long abstinence can actually reduce sperm quality. Every 1–2 days during the window is ideal.</li>
<li><strong>"Day 14 is ovulation day for everyone."</strong> Ovulation is 12–14 days before your <em>next</em> period — which lands all over the calendar depending on cycle length.</li>
</ul>

<h2>When to Ask for Help</h2>
<p>Under 35: after 12 months of well-timed trying. 35+: after 6 months. Right away if you have very irregular cycles, known reproductive conditions, or a partner with known fertility issues. Asking early is not giving up — it is gathering information.</p>

<h2>The Other Half: Male Fertility Quick Wins</h2>
<p>Roughly 40–50% of conception delays involve a male factor, and sperm regenerate on a ~72-day cycle — meaning changes made today show up in about ten weeks. The highest-impact moves:</p>
<ul>
<li><strong>Cool things down.</strong> Skip hot tubs and saunas, and keep laptops off laps. Sperm production is temperature-sensitive.</li>
<li><strong>Same lifestyle rules.</strong> No smoking, minimal alcohol, Mediterranean-style eating, and regular (not extreme) exercise all measurably improve sperm parameters.</li>
<li><strong>Check medications.</strong> Testosterone supplements in particular can shut down sperm production — ask the prescriber before TTC.</li>
<li><strong>A semen analysis is cheap and fast.</strong> If months are passing, this simple test should happen early, not as a last resort.</li>
</ul>

<h2>Your First Three Months TTC: A Simple Plan</h2>
<table>
<thead><tr><th>Month</th><th>Focus</th></tr></thead>
<tbody>
<tr><td>1</td><td>Start prenatal vitamins (both partners can take fertility-supportive supplements), book preconception checkups, begin <a href="/blog/how-to-track-ovulation-ttc">tracking your cycle</a> to learn your pattern.</td></tr>
<tr><td>2</td><td>Dial in timing: OPKs plus cervical mucus, intercourse every 1–2 days through the fertile window. Clean up sleep, alcohol, and smoking for real.</td></tr>
<tr><td>3</td><td>Keep the routine, review what your tracking shows. Irregular data this far in is worth a doctor conversation now rather than at the 12-month mark.</td></tr>
</tbody>
</table>

<h2>TTC FAQ</h2>
<h3>How long does it take most couples to conceive?</h3>
<p>With well-timed trying, roughly 30% conceive in the first cycle, about 80% within six months, and 85–90% within a year. A few months of trying without success is statistically normal, not a red flag.</p>
<h3>Does coming off birth control delay pregnancy?</h3>
<p>For most methods, fertility returns within a cycle or two — many women conceive the first month after stopping the pill. The exception is the contraceptive injection, which can take several months to clear. There is no required "wash-out" period.</p>
<h3>Do ovulation apps really work?</h3>
<p>Apps are excellent record-keepers and decent predictors once they have several cycles of your data — but their forecasts are statistical guesses. Confirm with body signals (OPKs, cervical mucus) before trusting any app''s fertile-window highlight, especially with irregular cycles.</p>
<p><em>This article is for educational purposes only and is not medical advice. Always consult your healthcare provider before starting or changing any exercise, nutrition, or fertility plan.</em></p>',
  ARRAY['ttc', 'wellness', 'nutrition'],
  'https://images.unsplash.com/photo-1609220136736-443140cffec6?auto=format&fit=crop&w=1200&q=80',
  'Catalyst Mom Team',
  'draft'
)
ON CONFLICT (slug) DO NOTHING;
