import { useState, useEffect } from 'react';
import PageLayout from '@/components/layout/PageLayout';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { Activity, Baby, CheckCircle, Heart, Timer, User, Users, TrendingUp, CreditCard, Crown, AlertCircle, Settings, ClipboardList } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useWellnessData } from '@/hooks/useWellnessData';
import { NutritionSection } from '@/components/dashboard/NutritionSection';
import { PointsBalance } from '@/components/dashboard/PointsBalance';
import { Dialog, DialogContent, DialogTrigger } from '@/components/ui/dialog';
import { TTCTracker } from '@/components/ttc/TTCTracker';
import { TTCNutritionSection } from '@/components/ttc/TTCNutritionSection';
import { TTCCommunitySection } from '@/components/ttc/TTCCommunitySection';
import { TTCEducationalResources } from '@/components/ttc/TTCEducationalResources';
import { PregnancyTracker } from '@/components/pregnancy/PregnancyTracker';
import { PregnancyJournal } from '@/components/pregnancy/PregnancyJournal';
import { PregnancyWellnessDigest } from '@/components/pregnancy/PregnancyWellnessDigest';
import { PostpartumPrepGuide } from '@/components/pregnancy/PostpartumPrepGuide';
import { PregnancyCommunity } from '@/components/pregnancy/PregnancyCommunity';
import { useAuth } from '@/contexts/AuthContext';
import { useContentFilter } from '@/hooks/useContentFilter';
import JourneySelector from '@/components/onboarding/JourneySelector';
import SubscriptionStatus from '@/components/subscription/SubscriptionStatus';
import SubscriptionButton from '@/components/subscription/SubscriptionButton';
import AffiliateButton from '@/components/affiliate/AffiliateButton';
import { ProfileCompletionWidget } from '@/components/profile/ProfileCompletionWidget';

import { MonthlyChallenge } from '@/components/challenges/MonthlyChallenge';
import { PersonalizedCoachCard } from '@/components/wellness-coach/PersonalizedCoachCard';
import { PushNotificationPrompt } from '@/components/notifications/PushNotificationPrompt';

import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
