// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/search-blog-posts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function anonClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_blog_posts_default = defineTool({
  name: "search_blog_posts",
  title: "Search blog posts",
  description: "Search Catalyst Mom's published blog posts by keyword and optional tag. Returns slug, title, excerpt, tags, author, and published_at for the top matches.",
  inputSchema: {
    query: z.string().trim().default("").describe("Keyword to match in title, excerpt, or content. Empty returns most recent posts."),
    tag: z.enum(["pregnancy", "postpartum", "ttc", "wellness", "nutrition", "fitness"]).optional().describe("Optional category tag filter."),
    limit: z.number().int().min(1).max(25).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, tag, limit }) => {
    const supabase = anonClient();
    let q = supabase.from("blogs").select("slug, title, excerpt, tags, author, published_at").eq("status", "published").order("published_at", { ascending: false }).limit(limit);
    if (query) {
      const pattern = `%${query.replace(/[%_]/g, (m) => `\\${m}`)}%`;
      q = q.or(`title.ilike.${pattern},excerpt.ilike.${pattern},content.ilike.${pattern}`);
    }
    if (tag) q = q.contains("tags", [tag]);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function anonClient2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_blog_post_default = defineTool2({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch a single published Catalyst Mom blog post by slug, including the full HTML content, tags, author, and published date.",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("Blog post slug (from search_blog_posts).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = anonClient2();
    const { data, error } = await supabase.from("blogs").select("slug, title, excerpt, content, tags, author, featured_image_url, published_at").eq("status", "published").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No published post found for slug "${slug}".` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list-blog-tags.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var TAGS = [
  { tag: "pregnancy", description: "Prenatal fitness, symptoms, birth prep." },
  { tag: "postpartum", description: "Recovery, healing, core restoration, newborn life." },
  { tag: "ttc", description: "Trying to conceive: fertility, cycle, nutrition." },
  { tag: "wellness", description: "Mental health, stress, self-care, sleep." },
  { tag: "nutrition", description: "Meals, recipes, nutrients for each stage." },
  { tag: "fitness", description: "Workouts and movement for moms." }
];
var list_blog_tags_default = defineTool3({
  name: "list_blog_tags",
  title: "List blog tags",
  description: "List the category tags available for Catalyst Mom blog posts. Use these with search_blog_posts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(TAGS, null, 2) }],
    structuredContent: { tags: TAGS }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "catalyst-mom-mcp",
  title: "Catalyst Mom",
  version: "0.1.0",
  instructions: "Public tools for Catalyst Mom \u2014 a maternal wellness platform covering TTC, pregnancy, and postpartum. Use `list_blog_tags` to see categories, `search_blog_posts` to find articles by keyword and tag, and `get_blog_post` to read the full content of a specific post. This server exposes only published blog content; user data is not available.",
  tools: [search_blog_posts_default, get_blog_post_default, list_blog_tags_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
